name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          key: lintenv-flake8

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip flake8

      - name: Flake8 test
        run: |
          . venv/bin/activate
          flake8 flameshow

  spell:
    name: Spell Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          skip: "*.log,./tests/pprof_data/*,poetry.lock,./tests/stackcollapse_data"

      - uses: actions/setup-python@v4
        with:
          ignore_words_list: hello,world
          python-version: "3.10"
          architecture: "x64"

  black:
    name: black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          key: lintenv-black

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip black

      - name: Black test
        run: |
          . venv/bin/activate
          black --check --diff .
